name: Deploy to EC2 (Nest)

on:
  push:
    branches:
      - feature/nestjs-migration

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Build project
        run: npm run build

      - name: Debug workspace
        run: |
          echo "Current path:"
          pwd
          echo "Files in root:"
          ls -la
          echo "Looking for dist:"
          ls -la dist || echo "DIST NOT FOUND"

      # Upload compiled build
      - name: Upload build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "dist/*"
          target: "/home/ubuntu/server/careConnect-server"

      - name: Restart backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd /home/ubuntu/server/careConnect-server

            echo "Installing production dependencies..."
            npm ci --omit=dev --no-audit --no-fund

            echo "Restarting backend..."
            pm2 delete careconnect || true
            pm2 start dist/main.js --name careconnect

            pm2 save